In [121]:
import pandas as pd
import matplotlib as plt

In [122]:
transactions = pd.read_csv("./data/amazon-purchases.csv")

In [123]:
print(transactions.head())

   Order Date  Purchase Price Per Unit  Quantity Shipping Address State  \
0  2018-12-04                     7.98       1.0                     NJ
1  2018-12-22                    13.99       1.0                     NJ
2  2018-12-24                     8.99       1.0                     NJ
3  2018-12-25                    10.45       1.0                     NJ
4  2018-12-25                    10.00       1.0                     NJ

                                               Title ASIN/ISBN (Product Code)  \
0  SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...               B0143RTB1E
1  Betron BS10 Earphones Wired Headphones in Ear ...               B01MA1MJ6H
2                                                NaN               B078JZTFN3
3  Perfecto Stainless Steel Shaving Bowl. Durable...               B06XWF9HML
4                      Proraso Shaving Cream for Men               B00837ZOI0

        Category  Survey ResponseID
0   FLASH_MEMORY  R_01vNIayewjIIKMF
1     HEADPHONES  R_01vNIayewjIIKMF
2            NaN  R_01vNIayewjIIKMF
3  DISHWARE_BOWL  R_01vNIayewjIIKMF
4  SHAVING_AGENT  R_01vNIayewjIIKMF

In [124]:
transactions["Order Date"] = pd.to_datetime(transactions["Order Date"])

In [125]:
transactions_sorted = transactions.sort_values(["Survey ResponseID", "Order Date"], ascending=[True, True])

## Adding customer information

In [126]:
customers = pd.read_csv("./data/survey.csv")

### Formating Living state to match with Temperature Table
We use the living state of customer table to fill in missing values in the transaction table -> need to be in the same format

In [127]:
# Create a dictionary of state name mappings
state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

# Assuming your dataframe is called 'df' and the column with state names is called 'state'
customers["Q-demos-state"] = customers["Q-demos-state"].replace(state_abbrev)

### Mergin Dataframes

In [128]:
amazon_data = transactions.merge(customers, on="Survey ResponseID", how="left")

### Dealing with missing shipping addresses

Most of missing values in "Shipping Address State" can be filled by looking at "Q-demos-state" from the customer dataset -> we asume that the residence state is the same state as the shipping state

In [129]:
amazon_data.loc[amazon_data["Shipping Address State"].isna(), "Shipping Address State"] = amazon_data["Q-demos-state"] # Replacing missing Shipping Addresses with living address from ordering customer

amazon_data.loc[amazon_data["Shipping Address State"] == "PR", "Shipping Address State"] = amazon_data["Q-demos-state"] # There is a shipping address state called PR which could be Puerto Rico, we replace this with the living state of the customer ordering

## Adding Temperature information

In [130]:
weather = pd.read_csv("./Data/weather_data.csv")

print(weather["st_abb"].nunique()) # No weather information for Alaska and Hawaii
weather.head()

48

,Unnamed: 0,st_abb,st_code,date,stability,ppt,tmax,tmin,tavg,dday_a0C,...,dday_a25C,dday_a29C,dday_a30C,dday_a31C,dday_a32C,dday_a33C,dday_a34C,dday_b15C,dday_b18C,dday_b21C
0,1,AL,1,20170101,stable,25.626,13.849,4.712,9.280,9.280,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,5.877,8.733,11.720
1,2,AL,1,20170102,stable,40.827,17.970,12.968,15.469,15.469,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.061,2.901,5.578
2,3,AL,1,20170103,stable,54.893,19.500,13.828,16.664,16.665,...,0.001,0.0,0.0,0.0,0.0,0.0,0.0,0.352,1.958,4.478
3,4,AL,1,20170104,stable,0.048,19.158,8.744,13.951,13.951,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2.326,4.374,7.066
4,5,AL,1,20170105,stable,0.002,11.202,-0.147,5.527,5.714,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,9.494,12.473,15.473

In [131]:
weather["date"] = pd.to_datetime(weather["date"], format="%Y%m%d")
weather.rename(columns={"st_abb": "Shipping Address State"}, inplace=True)
weather.head()

,Unnamed: 0,Shipping Address State,st_code,date,stability,ppt,tmax,tmin,tavg,dday_a0C,...,dday_a25C,dday_a29C,dday_a30C,dday_a31C,dday_a32C,dday_a33C,dday_a34C,dday_b15C,dday_b18C,dday_b21C
0,1,AL,1,2017-01-01,stable,25.626,13.849,4.712,9.280,9.280,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,5.877,8.733,11.720
1,2,AL,1,2017-01-02,stable,40.827,17.970,12.968,15.469,15.469,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.061,2.901,5.578
2,3,AL,1,2017-01-03,stable,54.893,19.500,13.828,16.664,16.665,...,0.001,0.0,0.0,0.0,0.0,0.0,0.0,0.352,1.958,4.478
3,4,AL,1,2017-01-04,stable,0.048,19.158,8.744,13.951,13.951,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2.326,4.374,7.066
4,5,AL,1,2017-01-05,stable,0.002,11.202,-0.147,5.527,5.714,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,9.494,12.473,15.473

In [132]:
# Joining weather

data_combined = pd.merge(
    left=weather, 
    right=amazon_data,
    how='left',
    left_on=['Shipping Address State', 'date'],
    right_on=['Shipping Address State', 'Order Date'],
)

In [133]:
# Check for which states we have no temperature information
# AK, DC, HI, I did not reside in the United States
# We still leave them in the dataset for completnes 

data_grouped = data_combined.groupby("Shipping Address State")
#data_grouped["tavg"].count()

### Calculate Revenue

In [134]:
data_combined["Revenue"] = data_combined["Purchase Price Per Unit"] * data_combined["Quantity"]

### Remove the one value for 2024

In [135]:
data_combined  = data_combined[(data_combined['date'] < '2024-01-01')]

## CHECKPOINT: Saving complete combined dataset

In [136]:
data_combined.to_csv('./data/data_combined_full.csv')

# Further process data for next steps

In [150]:
# Needed Columns for the Hypothesis testing
data_needed = ["date", "Category", "Revenue", "Shipping Address State", "tavg", "ppt", "Survey ResponseID"]

transactions_temp = pd.read_csv("./Data/data_combined_full.csv", usecols=data_needed)
transactions_temp["date"] = pd.to_datetime(transactions_temp["date"]) # Formating Order date back to Datetime dtype, in read_csv you cant set column to datetime so need to do manually

transactions_temp.rename(columns={"date": "Order Date"}, inplace=True)

C:\Users\morit\AppData\Local\Temp\ipykernel_17560\1062587725.py:4: DtypeWarning: Columns (34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions_temp = pd.read_csv("./Data/data_combined_full.csv", usecols=data_needed)

### Creating an Dataframe with all dates and States

In [151]:
states = transactions_temp['Shipping Address State'].unique()

date_range = pd.date_range(
    start=transactions_temp['Order Date'].min(),
    end=transactions_temp['Order Date'].max(),
    freq='D'
)
print(transactions_temp['Order Date'].min())

date_state_combinations = pd.MultiIndex.from_product(
    [date_range, states],
    names=['Order Date', 'Shipping Address State']
)
full_index_df = pd.DataFrame(index=date_state_combinations).reset_index()

2017-01-01 00:00:00

In [152]:
Fashion = [
    "ACCESSORY", "ADULT_COSTUME", "APPAREL", "APPAREL_BELT", "APPAREL_GLOVES",
    "APPAREL_HEAD_NECK_COVERING", "APPAREL_PIN", "APPENDAGE_WARMER", "APRON",
    "ARM_SLEEVE", "Apparel", "BABY_JUMPER_WALKER", "BELTS", "BLAZER",
    "BLUE_LIGHT_BLOCKING_EYEGLASSES", "BODYSTOCKING", "BOOT", "BRA", "BRACELET",
    "BRA_UNDERWEAR_SET", "CHOLI", "COAT", "COORDINATED_OUTFIT", "CORRECTIVE_EYEGLASSES",
    "CORSET", "DRESS", "DUPATTA", "EARMUFF", "EARRING", "ETHNIC_WEAR",
    "FASHIONEARRING", "FASHIONNECKLACEBRACELETANKLET", "FASHIONOTHER", "FASHIONRING",
    "FASHION_JEWELRY", "FINEEARRING", "FINENECKLACEBRACELETANKLET", "FINERING",
    "FOOTWEAR", "GUILD_APPAREL", "GUILD_JEWELRY", "GUILD_SHOES", "HAT", "HOSIERY",
    "JEWELRY", "JEWELRY_SET", "KIMONO", "KURTA", "LEG_SLEEVE", "LEOTARD",
    "MOISTURIZING_SOCK_GLOVE", "NECKLACE", "NECKTIE", "NIGHTGOWN_NIGHTSHIRT",
    "ORCA_SHIRT", "OUTERWEAR", "OVERALLS", "PAJAMAS", "PANTS", "PIERCING_JEWELRY",
    "ROBE", "SANDAL", "SAREE", "SHIRT", "SHOES", "SHORTS", "SKIRT", "SLEEPWEAR",
    "SLIPPER", "SNOWSHOE", "SNOWSUIT", "SNOW_PANT", "SOCK", "SOCKSHOSIERY", "SUIT",
    "SUNGLASSES", "SUSPENDER", "SWEATER", "SWEATSHIRT", "SWIMWEAR", "SWIM_CAP",
    "TIGHTS", "TRACK_SUIT", "UNDERPANTS", "UNDERWEAR", "UNDERGARMENT_SLIP",
    "UNDERGARMENT_THIGH_SLIMMER", "UNION_SUIT", "VEST", "WATCH", "WATCHES", "WATCH_BAND"
]


Groceries = [
   "ALCOHOLIC_BEVERAGE", "BABY_FOOD", "BABY_FORMULA", "BAKING_CHOCOLATE", "BEER",
   "BEVERAGE", "BREAD", "BREAKFAST_CEREAL", "CAKE", "CANDY", "CEREAL",
   "CHOCOLATE_CANDY", "COFFEE", "CONDIMENT", "COOKIE", "CRACKER", "CULINARY_SALT",
   "DAIRY_BASED_BUTTER", "DAIRY_BASED_CHEESE", "DAIRY_BASED_CREAM",
   "DAIRY_BASED_DRINK", "DAIRY_BASED_ICE_CREAM", "DAIRY_BASED_PUDDING",
   "DAIRY_BASED_YOGURT", "DONUT", "DRINK_FLAVORED", "EDIBLE_OIL_VEGETABLE",
   "FLOUR", "FRUIT", "FRUIT_SNACK", "FUDGE", "GOURMET_FOOD", "GROCERY", "Grocery",
   "HEALTH_FOOD", "HONEY", "JERKY", "JUICE_AND_JUICE_DRINK", "LEGUME",
   "MEAL_REPLACEMENT_BEVERAGE", "MEAT_ALTERNATIVE", "MILK_SUBSTITUTE",
   "NON_DAIRY_CHEESE", "NON_DAIRY_CREAM", "NON_DAIRY_ICE_CREAM",
   "NON_DAIRY_PUDDING", "NON_DAIRY_YOGURT", "NOODLE", "NUTS", "NUT_AND_SEED",
   "NUT_BUTTER", "OLIVE", "PACKAGED_SOUP_AND_STEW", "PASTRY", "POPCORN",
   "PRETZEL", "PROTEIN_DRINK", "PROTEIN_SUPPLEMENT_POWDER", "PUFFED_SNACK",
   "RICE_MIX", "RICE_WINE", "SALAD_DRESSING", "SEAFOOD", "SEASONING",
   "SNACK_CHIP_AND_CRISP", "SNACK_FOOD", "SNACK_FOOD_BAR", "SNACK_MIX",
   "SPORTS_DRINK", "SUGAR", "SUGAR_CANDY", "SUGAR_SUBSTITUTE", "SYRUP", "TEA",
   "TOFU", "VEGETABLE", "VEGETARIAN_EGG_SUBSTITUTE", "WATER"
]

In [153]:
mask_fashion = transactions_temp["Category"].isin(Fashion)
Fashion_transactions = transactions_temp[mask_fashion]
Fashion_transactions = Fashion_transactions.sort_values(["Order Date"]).copy() # .copy() to create new dataframe in memory and not a pd view


mask_groceries = transactions_temp["Category"].isin(Groceries)
Grocerie_transactions = transactions_temp[mask_groceries]
Grocerie_transactions = Grocerie_transactions.sort_values(["Order Date"]).copy()

In [154]:
Grocerie_transactions = Grocerie_transactions.sort_values("Order Date", ascending=True)

#Grocerie_transactions_grouped = Grocerie_transactions.groupby(["Order Date", "Shipping Address State"]).agg({"Revenue": "sum", "tavg":"first", "ppt": "first", "Survey ResponseID": lambda x: list(set(x))})
Grocerie_transactions_grouped = Grocerie_transactions.groupby(["Order Date", "Shipping Address State"]).agg({"Revenue": "sum", "Survey ResponseID": lambda x: list(set(x))})

Grocerie_transactions_grouped.reset_index(["Order Date", "Shipping Address State"], inplace=True)

In [155]:
Fashion_transactions = Fashion_transactions.sort_values("Order Date", ascending=True)

#Grocerie_transactions_grouped = Grocerie_transactions.groupby(["Order Date", "Shipping Address State"]).agg({"Revenue": "sum", "tavg":"first", "ppt": "first", "Survey ResponseID": lambda x: list(set(x))})
Fashion_transactions_grouped = Fashion_transactions.groupby(["Order Date", "Shipping Address State"]).agg({"Revenue": "sum", "Survey ResponseID": lambda x: list(set(x))})

Fashion_transactions_grouped.reset_index(["Order Date", "Shipping Address State"], inplace=True)

## Joining dataframes

## Grocieries

In [156]:
groceries_combined = pd.merge(
    left=full_index_df, 
    right=Grocerie_transactions_grouped,
    how='left',
    left_on=['Shipping Address State', 'Order Date'],
    right_on=['Shipping Address State', 'Order Date'],
)

groceries_combined_final = pd.merge(
    left= groceries_combined, 
    right= weather,
    how='left',
    left_on=['Shipping Address State', 'Order Date'],
    right_on=['Shipping Address State', 'date'],
)

groceries_combined_final = groceries_combined_final.drop(columns=["Unnamed: 0", "st_code", "date", "stability"])

groceries_combined_final["Revenue"] = groceries_combined_final['Revenue'].fillna(0)

groceries_combined_final["Survey ResponseID"] = groceries_combined_final["Survey ResponseID"].fillna("")

In [157]:
groceries_combined_final.to_csv('./data/grocery_data.csv')

## Fashion

In [158]:
fashion_combined = pd.merge(
    left=full_index_df, 
    right=Fashion_transactions_grouped,
    how='left',
    left_on=['Shipping Address State', 'Order Date'],
    right_on=['Shipping Address State', 'Order Date'],
)

fashion_combined_final = pd.merge(
    left= fashion_combined, 
    right= weather,
    how='left',
    left_on=['Shipping Address State', 'Order Date'],
    right_on=['Shipping Address State', 'date'],
)

fashion_combined_final = fashion_combined_final.drop(columns=["Unnamed: 0", "st_code", "date", "stability"])

fashion_combined_final["Revenue"] = fashion_combined_final['Revenue'].fillna(0)

fashion_combined_final["Survey ResponseID"] = fashion_combined_final["Survey ResponseID"].fillna("")

In [159]:
fashion_combined_final.to_csv('./data/fashion_data.csv')